<?php


/*
function hk_site_alter_form_alter(&$form, &$form_state, $form_id) {
$path = drupal_get_path('module', 'hk_site_alter');
drupal_add_js($path . '/hk_site_alter.js', array('weight' => 1));
}*/


/* implements hook_flag_flag() */
function hk_site_alter_flag_flag($flag, $entity_id, $account, $flagging) {
  $flag1 = flag_get_flag($flag->name);
  GLOBAL $user;
  if ($flag1) {
    $result = db_query("SELECT COUNT(*) FROM flagging WHERE uid=:uid and fid=1", array(':uid' => $user->uid))->fetchField(); //fid = ID your flag
    $mlid = 795;
    if ($menu_link = menu_link_load($mlid)) {
      $menu_link['options']['attributes']['class'] = array('flagged');
      menu_link_save($menu_link);
    }
  }

}

/* implements hook_flag_unflag() */
function hk_site_alter_flag_unflag($flag, $entity_id, $account, $flagging) {
$flag1 = flag_get_flag($flag->name);
  GLOBAL $user;
  if ($flag1) {
    $result = db_query("SELECT COUNT(*) FROM flagging WHERE uid=:uid and fid=1", array(':uid' => $user->uid))->fetchField(); //fid = ID your flag
    if($result == 1) {
      $mlid = 795;
      if ($menu_link = menu_link_load($mlid)) {
        $menu_link['options']['attributes']['class'] = array('unflagged');
        menu_link_save($menu_link);
      }
    }
  }
}

function hk_site_alter_form_alter(&$form, &$form_state, $form_id) {
  /*if($form_id == 'simplenews_subscriptions_multi_block_form') {
    $form['newsletters']['#options'][322] = 'I want to be informed on future offers that might be comparable.';
  }
  */
  if($form_id == 'crm_core_profile_entry_form_kontaktformular') {
    $block = block_load('simplenews', '0');
    $block = _block_get_renderable_array(_block_render_blocks(array($block)));
    $output = drupal_render($block);
    $form_1 = drupal_get_form('simplenews_subscriptions_multi_block_form');
    //$form['field_activity_notes']['#suffix'] = render($form_1); 
    $form['newsletters'] = $form_1['newsletters'];
    $form['newsletters']['#weight'] = '36';
    $form['newsletters']['#tree'] = '1';
    $form['mail'] = $form_1['mail'];
    $form['mail']['#weight'] = '37';
    $form['mail']['#tree'] = '1';
    $form['mail']['#required'] = 0;
    
   $form['#submit'][] = 'hk_site_alter_subscriptions_page_form_submit';
  }
  if($form_id == 'crm_core_profile_entry_form_call') {
    $block = block_load('simplenews', '0');
    $block = _block_get_renderable_array(_block_render_blocks(array($block)));
    $output = drupal_render($block);
    //$form['field_phone']['#suffix'] = $output;
    $form_1 = drupal_get_form('simplenews_subscriptions_multi_block_form');
    //$form['field_activity_notes']['#suffix'] = render($form_1); 
    $form['newsletters'] = $form_1['newsletters'];
    $form['newsletters']['#weight'] = '36';
    $form['newsletters']['#tree'] = '1';
    $form['mail'] = $form_1['mail'];
    $form['mail']['#weight'] = '37';
    $form['mail']['#required'] = 0;
    $form['mail']['#tree'] = '1';
    $form['mail']['#required'] = 0;
    $form['#submit'][] = 'hk_site_alter_subscriptions_page_form_submit';
  } 
}

function hk_site_alter_subscriptions_page_form_submit($form,&$form_state) {
  global $user;  
    if(in_array("anonymous user", $user->roles)) {
      if(isset($form_state['input']['mail']) && !empty($form_state['input']['mail'])) {
        $email = $form_state['input']['mail']; 
      }      
    } else {
        $email = $user->mail;
    } 
  if(isset($form_state['input']['newsletters'])) {
    $newsletter_id = 322;
    simplenews_subscribe_user($email, $newsletter_id, $confirm = FALSE, $source = 'action', NULL);
  }  
}
