<?php
/**
 * @file
 * hk_ct.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function hk_ct_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Partially restored',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '05ab1694-efa1-475a-a8ee-eeb23370cd36',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331604,
          'entity_uuid' => '05ab1694-efa1-475a-a8ee-eeb23370cd36',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'First Occupancy',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0e2103c8-4432-4d1f-ad63-19ad8341eaab',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331533,
          'entity_uuid' => '0e2103c8-4432-4d1f-ad63-19ad8341eaab',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Modernised',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '104d70f3-645a-44b4-aeec-ee3b31505413',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331583,
          'entity_uuid' => '104d70f3-645a-44b4-aeec-ee3b31505413',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'First Occupancy after Renovation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '15657492-128a-4045-b460-4e714633be5e',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331548,
          'entity_uuid' => '15657492-128a-4045-b460-4e714633be5e',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Normal',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '586e11b0-8955-4b87-a0d4-2b770083ba6c',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331573,
          'entity_uuid' => '586e11b0-8955-4b87-a0d4-2b770083ba6c',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Completely Refurbished',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a0248044-7d28-463d-b99f-450981482832',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331594,
          'entity_uuid' => 'a0248044-7d28-463d-b99f-450981482832',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'In need of modernization',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a4839066-cc9e-4628-9a10-8ac1f77005ae',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331642,
          'entity_uuid' => 'a4839066-cc9e-4628-9a10-8ac1f77005ae',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'No Information',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c5bab5fa-6859-437d-8c49-a18adb016553',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331655,
          'entity_uuid' => 'c5bab5fa-6859-437d-8c49-a18adb016553',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Renovated',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c947b295-41c5-438c-b9ba-c9e341be3b3b',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331615,
          'entity_uuid' => 'c947b295-41c5-438c-b9ba-c9e341be3b3b',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd233a8c4-dd5d-4b7c-bbf1-94b1ae89a4fc',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331669,
          'entity_uuid' => 'd233a8c4-dd5d-4b7c-bbf1-94b1ae89a4fc',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'In need of renovation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'dabed431-4623-495d-9f8d-ff4f9a745bc5',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331628,
          'entity_uuid' => 'dabed431-4623-495d-9f8d-ff4f9a745bc5',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Well-Tended',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f7a3ef11-c081-4b98-801a-41217edb440d',
    'language' => 'de',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'status_quo',
    'translations' => array(
      'original' => 'de',
      'data' => array(
        'de' => array(
          'entity_type' => 'taxonomy_term',
          'language' => 'de',
          'source' => '',
          'status' => 1,
          'translate' => 0,
          'created' => 1480331559,
          'entity_uuid' => 'f7a3ef11-c081-4b98-801a-41217edb440d',
          'user_uuid' => 'b3b8435e-2b2b-4c6d-8048-5873b1c84a64',
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
